language: csharp
mono: none
dotnet: 3.1.101
solution: miceExplorationTool.sln

# whitelist
branches:
  only:
    - demo

services:
    #Enable docker service inside travis
    - docker

before_install:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    - dotnet restore
    - dotnet test
    #build the image
    - docker build --no-cache -t  laurencebrwn/mice-exploration-tool .
    #tag the build
    - docker tag laurencebrwn/mice-exploration-tool:latest laurencebrwn/mice-exploration-tool:v1
    #push the image to the repository
    - docker push laurencebrwn/mice-exploration-tool