language: csharp
mono: none
dotnet: 3.1.101
solution: miceExplorationTool.sln

# whitelist
branches:
  only:
    - master

services:
    #Enable docker service inside travis
    - docker

before_install:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    - dotnet restore
    - dotnet test
    #build the test image
    - docker build --no-cache -t  laurencebrwn/mice-exploration-tool .
    #no longer push to demo site
